import type { Product } from '@/types/product';

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Set de Globos Kuromi',
        image: '/products/destacados/kuromi_balloon.jpg',
        price: 12.99,
        category: 'Globos',
        character: 'Kuromi',
        colors: ['Rosado', 'Negro'],
        occasions: ['Birthday', 'Kids'],
        description: 'Combo tematico de 5 piezas para aire o helio, ideal para mesas principales.',
    },
    {
        id: 2,
        name: 'Combo de Piñata Mickey',
        image: '/products/destacados/combo.jpg',
        category: 'Piñatas',
        price: 12.99,
        character: 'Mickey',
        colors: ['Rojo', 'Amarillo', 'Negro'],
        occasions: ['Birthday', 'Kids'],
        description: 'Piñata cuadrada con relleno incluido para celebraciones infantiles llenas de color.',
    },
    {
        id: 3,
        name: 'Set de Globos Labubu',
        image: '/products/destacados/labubu.jpg',
        category: 'Globos',
        price: 12.99,
        character: 'Labubu',
        colors: ['Marron', 'Rosado'],
        occasions: ['Birthday', 'Kids'],
        description: 'Arreglo de globos con acabado tierno y moderno para fiestas personalizadas.',
    },
    {
        id: 4,
        name: 'Piñata Frozen',
        image: '/products/pinatas/pinata_frozen.png',
        category: 'Piñatas',
        character: 'Frozen',
        colors: ['Azul', 'Blanco'],
        occasions: ['Birthday', 'Kids'],
        description: 'Diseño escarchado con presencia protagonista para cumpleaños inspirados en hielo y fantasia.',
    },
    {
        id: 5,
        name: 'Piñata Pony',
        image: '/products/product-category/pinata_pony.jpg',
        category: 'Piñatas',
        price: 12.99,
        character: 'My Little Pony',
        colors: ['Morado', 'Rosado', 'Celeste'],
        occasions: ['Birthday', 'Kids'],
        description: 'Acabado alegre y pastel para fiestas infantiles con una paleta dulce y brillante.',
    },
    {
        id: 6,
        name: 'Afiche Spiderman',
        image: '/products/afiches/spiderman.jpeg',
        category: 'Afiches',
        price: 12.99,
        character: 'Spiderman',
        colors: ['Rojo', 'Azul'],
        occasions: ['Birthday', 'Kids'],
        description: 'Afiche decorativo para destacar la mesa principal o la entrada de la celebracion.',
    },
    {
        id: 7,
        name: 'Decoracion Feliz Cumple',
        image: '/products/destacados/feliz_cumple.jpg',
        category: 'Decoracion',
        character: 'Cumpleanos',
        price: 12.99,
        colors: ['Fucsia', 'Dorado', 'Azul'],
        occasions: ['Birthday'],
        description: 'Banda y cintillo holografico para una celebracion vibrante y lista para fotos.',
    },
    {
        id: 8,
        name: 'Piñata Artesanal Fiesta',
        image: '/products/pinatas/pinata1.jpg',
        category: 'Piñatas',
        character: 'Personalizado',
        price: 12.99,
        colors: ['Rosado', 'Azul', 'Amarillo'],
        occasions: ['Birthday', 'Kids'],
        description: 'Modelo base adaptable a la tematica del cliente, pensado para pedidos especiales.',
    },
];
